GET http://localhost:8080/order
Content-Type: application/json

###
GET http://localhost:8080/order/2020-04-06-01
Content-Type: application/json

###
GET http://localhost:8080/order/2020-04-03-01
Content-Type: application/json

###
GET http://localhost:8080/order/2023-05-02-09
Content-Type: application/json

###
GET http://localhost:8080/order/2023-05-02-09/total
Content-Type: application/json

###
GET http://localhost:8080/order/2020-04-03-01/total
Content-Type: application/json

###
GET http://localhost:8080/order/2020-04-06-01/total
Content-Type: application/json